server:
  port: 8981

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

  client:
    eureka-server-port: 8761
    serviceUrl:
      defaultZone: http://localhost:${eureka.client.eureka-server-port}/eureka/

spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mikewoo/microservice-demo-config
          # 账号密码替换为自己的github账号密码
          username: test@163.com
          password: 123456
          #超时时间
          timeout: 5
          #分支
          default-label: master