server:
  port: 8961

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

  client:
    eureka-server-port: 8761
    serviceUrl:
      defaultZone: http://localhost:${eureka.client.eureka-server-port}/eureka/

spring:
  application:
    name: microservice-gateway-with-springcloud-gateway
  zipkin:
    # base-url: http://localhost:9411/ #默认http通信的配置方式
    sender:
      type: kafka
    service:
      name: ${spring.application.name} #zipkin里看到的的service name
  kafka:
    bootstrap-servers: 192.168.33.100:9092 #集群的情况直接用“,”分割
  sleuth:
    sampler:
      probability: 1
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://MICROSERVICE-PRODUCT-SERVICE
          predicates:
            - Path=/products/**
          filters:
          - StripPrefix=1

        - id: order-service
          uri: lb://MICROSERVICE-ORDER-SERVICE-WITH-HYSTRIX
          predicates:
          - Path=/orders/**
          filters:
          - StripPrefix=1

# 调整Hystrix默认超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000