server:
  port: 8731

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

  client:
    eureka-server-port: 8761
    serviceUrl:
      defaultZone: http://localhost:${eureka.client.eureka-server-port}/eureka/

spring:
  application:
    name: microservice-order-service-with-ribbon

# 给某个服务配置Ribbon自定义的负载均衡策略
microservice-product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
