server:
  port: 8971

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

  client:
    eureka-server-port: 8761
    serviceUrl:
      defaultZone: http://localhost:${eureka.client.eureka-server-port}/eureka/

spring:
  application:
    name: microservice-gateway-with-zuul
  zipkin:
    # base-url: http://localhost:9411/ #默认http通信的配置方式
    sender:
      type: kafka
    service:
      name: ${spring.application.name} #zipkin里看到的的service name
  kafka:
    bootstrap-servers: 192.168.33.100:9092 #集群的情况直接用“,”分割
  sleuth:
    sampler:
      probability: 1

# 自定义转发规则
zuul:
  routes:
    microservice-product-service: /microservice/products/**
    microservice-order-service-with-hystrix: /microservice/orders/**

  # 忽略默认访问规则
  ignored-patterns: /*-product-service/**

# 调整Hystrix默认超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000